### ISSUE TITLE
Control and state reporting stops working after some time

### ISSUE THREAD

**Issue by dreisday** [dennis1804/homewizard-climate-hass#19] opened 2023-11-26 10:16 UTC
Control and state reporting of panel heater stops working after a period of time, the state freezes at its last reported state and controls stop responding. This can be resolved by restarting home assistant, but will once again stop working soon after. 

Running HA Core 2023.11.2

**Comment by dennis1804** [comment] 2023-11-27 17:31
Duplicate of #11, closing this one

**Closed** 2023-11-27 17:31 UTC
